# Generated by Django 4.0.6 on 2023-04-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=150)),
                ('top_food', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
                ('long', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_recom_APP.cities')),
                ('restaurant_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant_recom_APP.restaurant_details')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=250)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_recom_APP.restaurant')),
            ],
        ),
    ]
